// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	plumbing "github.com/go-git/go-git/v5/plumbing"
	mock "github.com/stretchr/testify/mock"

	v5 "github.com/go-git/go-git/v5"
)

// Worktree is an autogenerated mock type for the WorktreeInterface type
type Worktree struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0
func (_m *Worktree) Add(_a0 string) (plumbing.Hash, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 plumbing.Hash
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (plumbing.Hash, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) plumbing.Hash); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plumbing.Hash)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Commit provides a mock function with given fields: _a0, _a1
func (_m *Worktree) Commit(_a0 string, _a1 *v5.CommitOptions) (plumbing.Hash, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 plumbing.Hash
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *v5.CommitOptions) (plumbing.Hash, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, *v5.CommitOptions) plumbing.Hash); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plumbing.Hash)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *v5.CommitOptions) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWorktree creates a new instance of Worktree. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorktree(t interface {
	mock.TestingT
	Cleanup(func())
}) *Worktree {
	mock := &Worktree{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
