// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	config "github.com/go-git/go-git/v5/config"

	mock "github.com/stretchr/testify/mock"
)

// GitConfigParser is an autogenerated mock type for the ConfigParserInterface type
type GitConfigParser struct {
	mock.Mock
}

// GetSectionOption provides a mock function with given fields: _a0, _a1
func (_m *GitConfigParser) GetSectionOption(_a0 string, _a1 string) string {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetSectionOption")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// LoadConfig provides a mock function with given fields: _a0
func (_m *GitConfigParser) LoadConfig(_a0 config.Scope) (*config.Config, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for LoadConfig")
	}

	var r0 *config.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(config.Scope) (*config.Config, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(config.Scope) *config.Config); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.Config)
		}
	}

	if rf, ok := ret.Get(1).(func(config.Scope) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetConfig provides a mock function with given fields: _a0
func (_m *GitConfigParser) SetConfig(_a0 *config.Config) {
	_m.Called(_a0)
}

// NewGitConfigParser creates a new instance of GitConfigParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGitConfigParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *GitConfigParser {
	mock := &GitConfigParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
